package com.agueguen.clafout1s.game2048.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF4C4F69)
val onPrimaryLight = Color(0xFFDF8E1D)
val primaryContainerLight = Color(0xFFCCD0DA)
val onPrimaryContainerLight = Color(0xFF4C4F69)
val secondaryLight = Color(0xFF4C4F69)
val onSecondaryLight = Color(0xFFDC8A78)
val secondaryContainerLight = Color(0xFF7287FD)
val tertiaryLight = Color(0xFF1E66F5)
val onTertiaryLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFEFF1F5)
val surfaceLight = Color(0xFFFAF8FF)

val primaryDark = Color(0xFFCAD3F5)
val onPrimaryDark = Color(0xFFF5A97F)
val primaryContainerDark = Color(0xFF363A4F)
val onPrimaryContainerDark = Color(0xFFF0C6C6)
val secondaryDark = Color(0xFF24273A)
val onSecondaryDark = Color(0xFFEED49F)
val secondaryContainerDark = Color(0xFFB7BDF8)
val tertiaryDark = Color(0xFF1E66F5)
val onTertiaryDark = Color(0xFFFFFFFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF24273A)
val surfaceDark = Color(0xFF11131B)

val primaryLightColor = Color(0xFF4C4F69)
val onPrimaryLightColor = Color(0xFFDF8E1D)
val primaryContainerLightColor = Color(0xFFDD7878)
val onPrimaryContainerLightColor = Color(0xFF4C4F69)
val secondaryLightColor = Color(0xFF4C4F69)
val onSecondaryLightColor = Color(0xFFDC8A78)
val secondaryContainerLightColor = Color(0xFFDC8A78)
val tertiaryLightColor = Color(0xFF1E66F5)
val onTertiaryLightColor = Color(0xFFFFFFFF)
val errorLightColor = Color(0xFFBA1A1A)
val onErrorLightColor = Color(0xFFFFFFFF)
val errorContainerLightColor = Color(0xFFFFDAD6)
val onErrorContainerLightColor = Color(0xFF93000A)
val backgroundLightColor = Color(0xFFEFF1F5)
val surfaceLightColor = Color(0xFFFAF8FF)
